@host = localhost
@port = 5157
@base = http://{{host}}:{{port}}

###

GET {{base}} HTTP/1.1

###

# public string? Name { get; set; } 
# public string? Email { get; set; } 
# public string? Phone { get; set; } 
# public string? Password { get; set; } 
# public string? ConfirmationPassword { get; set; } 
# public double? Price { get; set; } 


# make sure [FromBody] is set in the controller

POST {{base}}/person HTTP/1.1
Content-Type: application/json

{
  "Name": "Tresten Pool",
  "Email": "trestenpool@gmail.com",
  "Phone": "361-446-2936",
  "Password": "password",
  "ConfirmationPassword": "password",
  "Dob": "1998-01-29",
  "Price": 100.0
}


###

# testing DateRangeValidator
POST {{base}}/person HTTP/1.1
Content-Type: application/json

{
  "Name": "Tresten Pool",
  "Email": "trestenpool@gmail.com",
  "Phone": "361-446-2936",
  "Password": "password",
  "ConfirmationPassword": "password",
  "Dob": "1999-01-29",
  "FromDate": "2010-01-01",
  "ToDate": "2001-01-01",
  "Price": 100.0
}

###

# [FromForm] is optional to have before the object being model binding in the controller

POST {{base}}/person HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Name=Tresten Pool&Email=trestenpool@gmail.com&Phone=361-446-2936

###

POST {{base}}/person HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Name=James French&Email=trestenpool@gmail.com&Phone=361-446-2936&Tags[0]=#happy&Tags[1]=#taken
